import multer from "multer";

const MAX_PDF_SIZE_BYTES = 10 * 1024 * 1024;

/**
 1. sourceRoutes.post("/upload", uploadSinglePdf, asyncHandler(uploadPdf)) creates a middleware chain: Request → Multer → Controller.
 2.  uploadSinglePdf = pdfUpload.single("file") is a middleware generated by Multer; you don't implement next() yourself.
 3.  Multer processes the incoming multipart/form-data, finds the "file" field, checks the PDF MIME type and 10 MB size limit,
    and stores the file in memory as req.file.buffer.
 4. If everything succeeds, Multer internally calls next(), so Express moves to asyncHandler(uploadPdf). If something fails, 
    Multer passes the error to Express instead.
 5. memoryStorage() is used because the file doesn't need to be saved on the server disk—the PDF bytes are kept in req.file.buffer and 
    then directly sent to Cloudinary.
 */

export const pdfUpload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: MAX_PDF_SIZE_BYTES },
    fileFilter: (_req, file, callback) => {
        if (file.mimetype === "application/pdf") {
            callback(null, true);
            return;
        }

        callback(new Error("Only PDF files are allowed"));
    },
});

export const uploadSinglePdf = pdfUpload.single("file");